/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AniColle;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jülide
 */
public class addanimeinfo extends javax.swing.JFrame {

    /**
     * Creates new form addanimeinfo
     */
    private adminpanel adding;
    public addanimeinfo(adminpanel addinfo) {
        this.adding=addinfo;
        initComponents();
    }

    private addanimeinfo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proinfo = new javax.swing.JTextField();
        stuinfo = new javax.swing.JTextField();
        sourceinfo = new javax.swing.JTextField();
        genreinfo = new javax.swing.JTextField();
        typeinfo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addpro = new javax.swing.JButton();
        seasoninfo = new javax.swing.JTextField();
        couinfo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addstu = new javax.swing.JButton();
        addsource = new javax.swing.JButton();
        addgenre = new javax.swing.JButton();
        addtype = new javax.swing.JButton();
        addseason = new javax.swing.JButton();
        addcou = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        proinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proinfoActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        jLabel2.setText("Genre");

        jLabel3.setText("Source");

        jLabel4.setText("Producer");

        jLabel5.setText("Studio");

        addpro.setText("Add");
        addpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproActionPerformed(evt);
            }
        });

        jLabel6.setText("Season");

        jLabel7.setText("Country");

        addstu.setText("Add");
        addstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstuActionPerformed(evt);
            }
        });

        addsource.setText("Add");
        addsource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsourceActionPerformed(evt);
            }
        });

        addgenre.setText("Add");
        addgenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgenreActionPerformed(evt);
            }
        });

        addtype.setText("Add");
        addtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtypeActionPerformed(evt);
            }
        });

        addseason.setText("Add");
        addseason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addseasonActionPerformed(evt);
            }
        });

        addcou.setText("Add");
        addcou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcouActionPerformed(evt);
            }
        });

        jLabel8.setText("Add Anime Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stuinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addstu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sourceinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addsource))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genreinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addgenre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(couinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addcou)))
                        .addGap(11, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addpro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addtype))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seasoninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addseason)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addpro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stuinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addstu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addsource)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(addgenre))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(addtype))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seasoninfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(addseason))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(addcou))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addgenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgenreActionPerformed
        try {
            String genreinfoo=genreinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `genres`(`genre_name`) VALUES(?)");
          		
               			
               ps.setString(1, genreinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           }
    }//GEN-LAST:event_addgenreActionPerformed

    private void proinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proinfoActionPerformed

    private void addproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproActionPerformed
        try {
            String producerinfoo=proinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `producers`(`producername`) VALUES(?)");
          		
               			
               ps.setString(1, producerinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           } 
                                       

    }//GEN-LAST:event_addproActionPerformed

    private void addstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstuActionPerformed
        try {
            String studioinfoo=stuinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `studios`(`studios_name`) VALUES(?)");
          		
               			
               ps.setString(1, studioinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           } 
    }//GEN-LAST:event_addstuActionPerformed

    private void addsourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsourceActionPerformed
        try {
            String sourceinfoo=sourceinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `sources`(`sourcename`) VALUES(?)");
          		
               			
               ps.setString(1, sourceinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           }
    }//GEN-LAST:event_addsourceActionPerformed

    private void addtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtypeActionPerformed
        try {
            String typeinfoo=typeinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `types`(`typename`) VALUES(?)");
          		
               			
               ps.setString(1, typeinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           }
    }//GEN-LAST:event_addtypeActionPerformed

    private void addseasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addseasonActionPerformed
       try {
            String seasoninfoo=seasoninfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `season`(`seasonname`) VALUES(?)");
          		
               			
               ps.setString(1, seasoninfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           }
    }//GEN-LAST:event_addseasonActionPerformed

    private void addcouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcouActionPerformed
        try {
            String couinfoo=couinfo.getText(); 
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        PreparedStatement ps = connect.prepareStatement("INSERT INTO `countries`(`countryname`) VALUES(?)");
          		
               			
               ps.setString(1, couinfoo); 
               
               ps.executeUpdate(); //							//execute the statement
               JOptionPane.showMessageDialog(null, "Data Inserted");		//display the message if it successful
           }catch(HeadlessException | SQLException ex){
             JOptionPane.showMessageDialog(null, "Data not Inserted");			//display the message if it is not done
           }
    }//GEN-LAST:event_addcouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addanimeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addanimeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addanimeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addanimeinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addanimeinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcou;
    private javax.swing.JButton addgenre;
    private javax.swing.JButton addpro;
    private javax.swing.JButton addseason;
    private javax.swing.JButton addsource;
    private javax.swing.JButton addstu;
    private javax.swing.JButton addtype;
    private javax.swing.JTextField couinfo;
    private javax.swing.JTextField genreinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField proinfo;
    private javax.swing.JTextField seasoninfo;
    private javax.swing.JTextField sourceinfo;
    private javax.swing.JTextField stuinfo;
    private javax.swing.JTextField typeinfo;
    // End of variables declaration//GEN-END:variables
}
