/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AniColle;



/**
 *
 * @author Jülide
 */
public class adminpanel extends javax.swing.JFrame {

    /**
     * Creates new form adminpanel
     */
    private animelist parenttt;
    public adminpanel(animelist adminpage) {
        this.parenttt=adminpage;
        initComponents();
    }

    private adminpanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addanimes = new javax.swing.JMenuItem();
        updatepisodes = new javax.swing.JMenuItem();
        updateanimes = new javax.swing.JMenuItem();
        infoadd = new javax.swing.JMenuItem();
        manageusers = new javax.swing.JMenu();
        viewallusers = new javax.swing.JMenuItem();
        deleteusers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        animenews = new javax.swing.JMenuItem();
        platformnews = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Management Panel");

        jMenu1.setText("Manage Animes");

        addanimes.setText("Add Animes");
        addanimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addanimesActionPerformed(evt);
            }
        });
        jMenu1.add(addanimes);

        updatepisodes.setText("Update Episodes");
        updatepisodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepisodesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updatepisodesMousePressed(evt);
            }
        });
        jMenu1.add(updatepisodes);

        updateanimes.setText("Update Animes");
        updateanimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateanimesMousePressed(evt);
            }
        });
        jMenu1.add(updateanimes);

        infoadd.setText("Add Anime Info");
        infoadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoaddActionPerformed(evt);
            }
        });
        jMenu1.add(infoadd);

        jMenuBar1.add(jMenu1);

        manageusers.setText("Manage Users");
        manageusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageusersActionPerformed(evt);
            }
        });

        viewallusers.setText("View all Users");
        viewallusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallusersActionPerformed(evt);
            }
        });
        manageusers.add(viewallusers);

        deleteusers.setText("Delete Users");
        deleteusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteusersActionPerformed(evt);
            }
        });
        manageusers.add(deleteusers);

        jMenuBar1.add(manageusers);

        jMenu3.setText("Manage News");

        animenews.setText("Anime News");
        animenews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animenewsActionPerformed(evt);
            }
        });
        jMenu3.add(animenews);

        platformnews.setText("Platform News");
        platformnews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformnewsActionPerformed(evt);
            }
        });
        jMenu3.add(platformnews);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addanimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addanimesActionPerformed
       new Addingpanel(this).setVisible(true);
       
    }//GEN-LAST:event_addanimesActionPerformed

    private void infoaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoaddActionPerformed
       new addanimeinfo(this).setVisible(true);
       
    }//GEN-LAST:event_infoaddActionPerformed

    private void platformnewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformnewsActionPerformed
        new platformnews(this).setVisible(true);
    }//GEN-LAST:event_platformnewsActionPerformed

    private void manageusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersActionPerformed
       
    }//GEN-LAST:event_manageusersActionPerformed

    private void deleteusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteusersActionPerformed
       new deleteuser(this).setVisible(true);   
    }//GEN-LAST:event_deleteusersActionPerformed

    private void viewallusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallusersActionPerformed
      new viewuser(this).setVisible(true);
    }//GEN-LAST:event_viewallusersActionPerformed

    private void animenewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animenewsActionPerformed
        new addnews(this).setVisible(true);
    }//GEN-LAST:event_animenewsActionPerformed

    private void updatepisodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepisodesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepisodesMouseClicked

    private void updatepisodesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepisodesMousePressed
        new updatesanime(this).setVisible(true);
    }//GEN-LAST:event_updatepisodesMousePressed

    private void updateanimesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateanimesMousePressed
        new updateanime(this).setVisible(true);
    }//GEN-LAST:event_updateanimesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addanimes;
    private javax.swing.JMenuItem animenews;
    private javax.swing.JMenuItem deleteusers;
    private javax.swing.JMenuItem infoadd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu manageusers;
    private javax.swing.JMenuItem platformnews;
    private javax.swing.JMenuItem updateanimes;
    private javax.swing.JMenuItem updatepisodes;
    private javax.swing.JMenuItem viewallusers;
    // End of variables declaration//GEN-END:variables
}
