package AniColle;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class animelist extends javax.swing.JFrame {

    /**
     * Creates new form animelist
     */
    public animelist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entryid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entrypass = new javax.swing.JPasswordField();
        logbutton = new javax.swing.JButton();
        regbutton = new javax.swing.JButton();
        logwarn = new javax.swing.JLabel();
        logadmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AniColle");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setText("Username");

        entryid.setBackground(new java.awt.Color(240, 240, 240));
        entryid.setForeground(new java.awt.Color(153, 51, 0));
        entryid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Password");

        entrypass.setForeground(new java.awt.Color(153, 51, 0));

        logbutton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        logbutton.setForeground(new java.awt.Color(153, 51, 0));
        logbutton.setText("Login");
        logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttonActionPerformed(evt);
            }
        });

        regbutton.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        regbutton.setForeground(new java.awt.Color(153, 51, 0));
        regbutton.setText("Register");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });

        logadmin.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        logadmin.setForeground(new java.awt.Color(153, 51, 0));
        logadmin.setText("Admin");
        logadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(entryid)
                            .addComponent(entrypass, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(logwarn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regbutton))
                        .addGap(18, 18, 18)
                        .addComponent(logadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logwarn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logbutton)
                    .addComponent(logadmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(regbutton)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryidActionPerformed

    private void logbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbuttonActionPerformed
      String eid = entryid.getText();				//FOR GETTING TEXT INFORMATION ABOUT STUDENT ID
String epass = entrypass.getText();		//FOR GETTING PASS INFORMATION ABOUT STUDENT PASSWORD
													//THESE VARIABLES PROVIDE US TO KEEP INFORMATION COMING FROM TWO TEXT AREAS
 Connection con;			
        PreparedStatement ps;

try
                        {
                            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
                            
                            //SQL STATEMENTS FOR CONTROL THE LOGIN INFORMATION WITH DATABASE INFORMATION
                            ps = con.prepareStatement("SELECT `userid`, `password` FROM  `users` WHERE `userid` = ? AND `password` = ?");
                            ps.setString(1, eid);
            ps.setString(2, epass);
         
            ResultSet result = ps.executeQuery();
                           
                       if(result.next()){			//IF THE INFORMATION COMING FROM TEXT AREAS ARE SAME WITH DATABASE INFORMATIONS, LOGIN IS ACCEPTED
       
 
            JOptionPane.showMessageDialog(null, "You are redirected to timeline, please wait...");			//SHOW THE MESSAGE TO USER
            
         logwarn.setVisible(false);
        
         new usertimeline (this).setVisible(false);			//REDIRECTING TO STUDENT PAGE 
         new usertimeline(eid).setVisible(true);		
         
         dispose();										//SHUT THE LOGIN PAGE
         
         
        //IF THE INFORMATION COMING FROM TEXT AREAS ARE NOT SAME WITH DATABASE, YOU CAN'T LOGIN THE SYSTEM AND YOU TAKE AN ERROR MESSAGE IN VARY TEXTS. 
      }else {
         JOptionPane.showMessageDialog(null, "Something is wrong.");
         logwarn.setText("Password or ID is wrong, please try again.");
         logwarn.setVisible(true);
        // adminwarning.setVisible(false);
                                    
 
if ("".equals(epass) && "".equals(eid)) {			//IF BOTH OF TEXTAREAS ARE NULL
logwarn.setText("Please, enter the ID and the password!");
entryid.requestFocusInWindow();									//FOCUS ON STUDENT ID TEXT AREA FOR ENTRYING



} else if ("".equals(eid)) {							//IF STUDENT ID IS NULL
logwarn.setText("Please, enter the ID!");
entryid.requestFocusInWindow();							//FOCUS ON STUDENT ID TEXT AREA FOR ENTRYING


			
} else if ("".equals(epass)) {					//IF STUDENT PASSWORD AREA IS NULL
logwarn.setText("Please, enter the password!");
entrypass.requestFocusInWindow();							//FOCUS ON STUDENT PASSWORD ARE FOR ENTRYING

} }
                         } catch (SQLException ex) {
            Logger.getLogger(animelist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logbuttonActionPerformed

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbuttonActionPerformed
    new register(this).setVisible(true);
    dispose();
    }//GEN-LAST:event_regbuttonActionPerformed

    private void logadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logadminActionPerformed
        String aid = entryid.getText();				//GETTING THE TEXT FROM TEXT AREA
        String apass = entrypass.getText();				//GETTING THE PASSWORD FROM PASSWORD AREA
        //IF TEXTAREAS ARE NULL
        Connection connect;
        PreparedStatement pse;

        try
        {
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");

            //SQL STATEMENTS FOR CONTROL THE LOGIN INFORMATION WITH DATABASE INFORMATION
            pse = connect.prepareStatement("SELECT `adminid`, `adminpass` FROM  `admin` WHERE `adminid` = ? AND `adminpass` = ?");
            pse.setString(1,aid);
            pse.setString(2, apass);

            ResultSet resultt = pse.executeQuery();

            if(resultt.next()){			//IF THE INFORMATION COMING FROM TEXT AREAS ARE SAME WITH DATABASE INFORMATIONS, LOGIN IS ACCEPTED

                JOptionPane.showMessageDialog(null, "You are redirected to admin page, please wait...");			//SHOW THE MESSAGE TO USER
                new adminpanel(this).setVisible(true); 
                logwarn.setVisible(false);
                dispose();

                //SHUT THE LOGIN PAGE
            } else {
                JOptionPane.showMessageDialog(null, "Something is wrong.");				//IF THE INFORMATION ABOUT LOGIN ARE NOT SAME WITH THE VALUES
                logwarn.setText("Password or ID is wrong, please try again.");
                logwarn.setVisible(true);						//SHOW THE WARNINGS RELATED TO IT

                if ("".equals(apass) && "".equals(aid)) {			//IF BOTH OF AREAS ARE NULL
                    logwarn.setText("Please, enter the ID and the password!");
                    entryid.requestFocusInWindow();									//FOCUS ON ADMIN ID AREA FOR ENTRYING

                } else if ("".equals(aid)) {								//IF ADMIN ID AREA IS NULL
                    logwarn.setText("Please, enter the ID!");
                    entryid.requestFocusInWindow();										//FOCUS ON ADMIN ID AREA FOR ENTRYING

                } else if ("".equals(apass)) {						//IF ADMIN PASSWORD ARE IS NULL
                    logwarn.setText("Please, enter the password!");
                    entrypass.requestFocusInWindow();							//FOCUS ON PASSWORD AREA FOR ENTRYING

                }}}catch (SQLException ex) {
            Logger.getLogger(animelist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(animelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(animelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(animelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(animelist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new animelist().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entryid;
    private javax.swing.JPasswordField entrypass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logadmin;
    private javax.swing.JButton logbutton;
    private javax.swing.JLabel logwarn;
    private javax.swing.JButton regbutton;
    // End of variables declaration//GEN-END:variables
}
