/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AniColle;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jülide
 */
public class Viewplatformnews extends javax.swing.JFrame {

    /**
     * Creates new form Viewplatformnews
     */
    private usertimeline getnew2;
    public Viewplatformnews(usertimeline getfor2) {
        this.getnew2=getfor2;
        initComponents();
        
    }
    
     @SuppressWarnings("OverridableMethodCallInConstructor")
    public Viewplatformnews (String newsofpl) {	//for taking the student name whose login to system 	
        initComponents();
      
       plnewss.setText(newsofpl);
      plnewss.setVisible(false);
       
        
       
       try {
            String alnew=plnewss.getText();
        Connection cd;
            cd = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        Statement st = (Statement) cd.createStatement();
        try(ResultSet rs = st.executeQuery("Select * FROM "+alnew+"")) { //connect to database table
            int colcount = rs.getMetaData().getColumnCount(); //take columns from database as have how much columns and put on these things
            DefaultTableModel tm = new DefaultTableModel(); //creating model
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); //Adding columns to table by names which are the same as database
            while(rs.next())
                {
                    Object[] row = new Object[colcount];				//put data on these columns 
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);						//from index 0 to index i-1
                    tm.addRow(row);
                }
            plnewstable.setModel(tm);
        }
        cd.close();     //burda veritabanı bağlantısını kapatmıs														//disconnect
    } catch (SQLException ex) {     //burası da veritabanına bağlanamazsa vereceği uyarı için kullanılmıs
            Logger.getLogger(MyQuery.class.getName()).log(Level.SEVERE, null, ex);
    }
       
       
       
    }

    private Viewplatformnews() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnewspane = new javax.swing.JScrollPane();
        plnewstable = new javax.swing.JTable();
        plnewss = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plnewstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));
        plnewstable.setCellSelectionEnabled(true);
        plnewstable.setMaximumSize(new java.awt.Dimension(4124, 2313));
        plnewstable.setMinimumSize(new java.awt.Dimension(500, 500));
        plnewstable.setPreferredSize(new java.awt.Dimension(500, 500));
        plnewstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plnewstableMouseClicked(evt);
            }
        });
        plnewspane.setViewportView(plnewstable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(971, Short.MAX_VALUE)
                .addComponent(plnewss)
                .addGap(137, 137, 137))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(plnewspane, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(plnewss)
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(plnewspane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plnewstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plnewstableMouseClicked
        boolean b= plnewstable.isEditing();
        if(b==false){
            JOptionPane.showMessageDialog(null,"You can't edit the news.");
        }
    }//GEN-LAST:event_plnewstableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewplatformnews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewplatformnews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewplatformnews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewplatformnews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewplatformnews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane plnewspane;
    private javax.swing.JLabel plnewss;
    private javax.swing.JTable plnewstable;
    // End of variables declaration//GEN-END:variables
}
