/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AniColle;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jülide
 */
public class viewuser extends javax.swing.JFrame {

    /**
     * Creates new form viewuser
     */
    private adminpanel pare;
    public viewuser(adminpanel viewuserspanel) {
        this.pare=viewuserspanel;
        initComponents();
        try {
              //connection and statement informations 
        Connection conct = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        Statement st = (Statement) conct.createStatement();
			//try the result set with the SQL statement and execute the statement
	  try(ResultSet rs = st.executeQuery("SELECT `nickname`,`age`,`email` FROM `users` ") ) { 
            int counter = rs.getMetaData().getColumnCount(); 	//count the column numbers from the database
            DefaultTableModel tm = new DefaultTableModel();		//create a default table model
            for(int i = 1;i<=counter;i++)
               
                tm.addColumn(rs.getMetaData().getColumnName(i));		//add columns from coming the database
            while(rs.next())				//while statement
                {
					Object[] row = new Object[counter];			//identify the rows according to counter
                    for(int i=1;i<=counter;i++)					//start the loop for the counter
                        row[i-1] = rs.getObject(i);			//put the objects to the columns
         
                    tm.addRow(row);
                }
            usertable.setModel(tm);
        }
        conct.close();								//close the connection
    } catch (SQLException ex) {
            Logger.getLogger(viewuser.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private viewuser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userpane = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        viewuserss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));
        userpane.setViewportView(usertable);

        viewuserss.setText("Refresh");
        viewuserss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewuserssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userpane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewuserss)
                        .addGap(243, 243, 243))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(viewuserss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userpane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewuserssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewuserssActionPerformed
 try {
              //connection and statement informations 
        Connection conct = DriverManager.getConnection("jdbc:mysql://localhost:3306/anicolle?useUnicode=true&characterEncoding=UTF-8", "afrodeitt", "closemyeyes");
        Statement st = (Statement) conct.createStatement();
			//try the result set with the SQL statement and execute the statement
	  try(ResultSet rs = st.executeQuery("SELECT `nickname`,`age`,`email` FROM `users` ") ) { 
            int counter = rs.getMetaData().getColumnCount(); 	//count the column numbers from the database
            DefaultTableModel tm = new DefaultTableModel();		//create a default table model
            for(int i = 1;i<=counter;i++)
               
                tm.addColumn(rs.getMetaData().getColumnName(i));		//add columns from coming the database
            while(rs.next())				//while statement
                {
					Object[] row = new Object[counter];			//identify the rows according to counter
                    for(int i=1;i<=counter;i++)					//start the loop for the counter
                        row[i-1] = rs.getObject(i);			//put the objects to the columns
         
                    tm.addRow(row);
                }
            usertable.setModel(tm);
        }
        conct.close();								//close the connection
    } catch (SQLException ex) {
            Logger.getLogger(viewuser.class.getName()).log(Level.SEVERE, null, ex);
    }        
         
    }//GEN-LAST:event_viewuserssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane userpane;
    private javax.swing.JTable usertable;
    private javax.swing.JButton viewuserss;
    // End of variables declaration//GEN-END:variables
}
